dist: xenial
language: java
sudo: false
jdk: oraclejdk11
before_install:
  - chmod +x mvnw
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
after_success:
  - mvn clean test jacoco:report coveralls:jacoco
cache:
  diretories:
    - $HOME/.m2
    - $HOME/.sonar/cache