dist: xenial
language: java
sudo: false
jdk: oraclejdk11
install: true
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: "marcoslsouza"
    token:
      secure: "**************************"
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  diretories:
    - $HOME/.m2
    - $HOME/.sonar/cache