dist: xenial
language: java
sudo: false
jdk: oraclejdk11
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  diretories:
    - $HOME/.m2