dist: xenial
language: java
sudo: false
jdk: oraclejdk11
before_install:
  - chmod +x mvnw
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marcoslsouza_biblioteca
cache:
  diretories:
    - $HOME/.m2
    - $HOME/.sonar/cache