dist: xenial
language: java
sudo: false
jdk: oraclejdk11
install: true
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: "marcoslsouza"
    token:
      secure: "**************************"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marcoslsouza_biblioteca
cache:
  diretories:
    - $HOME/.m2
    - $HOME/.sonar/cache